services:
  - type: web
    name: django-notes-crud
    plan: free
    env: python
    buildCommand: "bash ./render_build.sh"
    startCommand: "gunicorn --pythonpath django_CRUD django_CRUD.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: django_CRUD.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
